### ISSUE TITLE
Wolfenstein parametrization of CKM

### ISSUE THREAD

**Issue by bednya** [flav-io/flavio#106]
I am trying to read the VCKMIN block from an SLHA file.
The problem is that I can not make flavio use Wolfenstein parametrization by
https://github.com/flav-io/flavio/blob/2e84dea36a2a00b5be490554fdaabac653ea85f4/flavio/data/config.yml#L12
(also referenced here  - https://flav-io.github.io/docs/customize.html)

However, the statement (taken from closed issue #11, which seems obsolete/abandoned) 
```python
flavio.config['implementation']['CKM matrix'] = 'Wolfenstein'
```
is (still) working, so

```python
import flavio
print('flavio ver:', flavio.__version__)
old_pars = flavio.default_parameters.get_central_all()
old_ckm_tree = flavio.physics.ckm.get_ckm(old_pars)
print('default ckm:', old_ckm_tree)

flavio.default_parameters.set_constraint('laC',0.22535)
flavio.default_parameters.set_constraint('A', 0.811)
flavio.default_parameters.set_constraint('rhobar', 0.131)
flavio.default_parameters.set_constraint('etabar', 0.345)

pars = flavio.default_parameters.get_central_all()
flavio.config['CKM matrix'] = 'Wolfenstein'

new_ckm_still_tree = flavio.physics.ckm.get_ckm(pars)
print('the same ckm:', new_ckm_still_tree)

flavio.config['implementation']['CKM matrix'] = 'Wolfenstein'
new_ckm_wolfenstein = flavio.physics.ckm.get_ckm(pars)
print('now new ckm:', new_ckm_wolfenstein)

```
gives:
```console
flavio ver: 2.0.0
default ckm: [[ 0.97439779+0.00000000e+00j  0.2248    +0.00000000e+00j
   0.00110513-3.56252619e-03j]
 [-0.22464666-1.46526356e-04j  0.97352564-3.38045973e-05j
   0.04221   +0.00000000e+00j]
 [ 0.00841306-3.46824795e-03j -0.04137812-8.00147690e-04j
   0.9991018 +0.00000000e+00j]]
the same ckm: [[ 0.97439779+0.00000000e+00j  0.2248    +0.00000000e+00j
   0.00110513-3.56252619e-03j]
 [-0.22464666-1.46526356e-04j  0.97352564-3.38045973e-05j
   0.04221   +0.00000000e+00j]
 [ 0.00841306-3.46824795e-03j -0.04137812-8.00147690e-04j
   0.9991018 +0.00000000e+00j]]
now new ckm: [[ 0.97427186+0.00000000e+00j  0.22534861+0.00000000e+00j
   0.00124748-3.28535540e-03j]
 [-0.22520886-1.31826031e-04j  0.97343967-3.04912971e-05j
   0.04118445+0.00000000e+00j]
 [ 0.00806661-3.19813332e-03j -0.04040623-7.39726686e-04j
   0.99914538+0.00000000e+00j]]
```

**Comment by DavidMStraub** [comment]
Yes, that's obviously a typo in the comment, is this what you're referring to?

**Comment by bednya** [comment]
Thanks, @DavidMStraub!
Yes, this indeed seems to be a documentation issue:)

BTW, is it right that the code mentioned in  #11 
(https://flav-io.github.io/apidoc/flavio/io/flha.m.html#flavio.io.flha.read_ckm)
was completely purged from the current version?

**Comment by DavidMStraub** [comment]
Yes, the `flha` module was removed long ago, see
https://github.com/flav-io/flavio/releases/tag/v0.30
https://github.com/flav-io/flavio/releases/tag/v1.0

**Comment by bednya** [comment]
Thanks for the clarification! Should I close the issue or wait until the documentation update:)?

**Comment by DavidMStraub** [comment]
Don't close it unless it's fixed. The open source spirit would suggest you fix it yourself 😉

**Comment by peterstangl** [comment]
@bednya, thanks for reporting the typos and fixing them!
I have merged your PRs, so I close this issue.
