### ISSUE TITLE
Measurements for RK*.

### ISSUE THREAD

**Issue by jackypheno** [flav-io/flavio#109]
@peterstangl @DavidMStraub 

my_obs = ['(<Rmue>(B0->K*ll), q2min=1.1, q2max=6)']
FL = FastLikelihood(name='test', observables=my_obs)
FL.make_measurement(threads=4)

fails to find measurements for the RK*.  

`line 74, in __init__
    assert missing_obs == set(), "No measurement found for the observables: " + str(missing_obs)
AssertionError: No measurement found for the observables: {'(<Rmue>(B0->K*ll), q2min=1.1, q2max=6)'}`

Please have a look. 
Thanks

**Comment by DavidMStraub** [comment]
It should be a tuple, not a string.

**Comment by jackypheno** [comment]
@DavidMStraub 

Thank so much!
