### ISSUE TITLE
Isuues with importing Flavio

### ISSUE THREAD

**Issue by Joro20** [flav-io/flavio#115]
Hi,

I was trying to install Flavio, but I'm not an experienced user of this coding platform. I was following the instructions for prerequisites and step by step guide to install it. But I'm having several issues:
1) First of all, while checking the prerequisites, I found this
`joydeep@:~$ python3 --version
Python 3.8.5
`
`joydeep@:~$ pip3 --version
pip 20.2.2 from /home/joydeep/.local/lib/python3.5/site-packages/pip (python 3.5)`
is this okay ?
2) Secondly, I went with this environment to install flavio and it appeared to me that it went without any trouble! But, with `apt list --installed` command, it doesn't show me flavio in it ! 
3) Then, when I do `import flavio`, it shows me this error
`import: not authorized `flavio' @ error/constitute.c/WriteImage/1028.`

Please help. 
Thanks,
Joydeep

**Comment by DavidMStraub** [comment]
Hi,

first of all, your `pip` points to a Python 3.5 executable, while your `python3` is a Python 3.8 executable. So you have some serious issues with your Python setup. Workaround: use `python3 -m pip` instead of `pip`.

Secondly, `apt` has nothing to do with a package installed with `pip`, so your 2. is moot.

I suggest you install some common package (e.g. `numpy` or `pandas`). Once you made that work and still have problems with `flavio`, please reopen this issue.

**Comment by Joro20** [comment]
@DavidMStraub , Thanks for your reply. 

> Workaround: use python3 -m pip instead of pip.

I did that for the flavio installation. I followed the instructions given here [https://flav-io.github.io/docs/installation.html](url) and used the command `python3 -m pip install flavio`

> I suggest you install some common package (e.g. numpy or pandas) with pip.

I found that all those packages you mentioned here are already installed ! And, I\m still having the same issue.

**Comment by DavidMStraub** [comment]
Please try if matplotlib works.

**Comment by Joro20** [comment]
matplotlib is also installed already.

**Comment by DavidMStraub** [comment]
Where are you running `import flavio`?

**Comment by Joro20** [comment]
In my home directory. Actually I don't see any other relevant places from where should I run it! Like I said, I don't see any trace of the package 'flavio' anywhere in my system!

**Comment by DavidMStraub** [comment]
Sorry but apparently you have never run a Python program before. Please google "Python" and learn at least the very basics rather then bothering the developers with an issue report.

You have to run it in a Python interpreter, not the shell.

**Comment by Joro20** [comment]
Ah, okay. So, I just Googled 'Python Interpreter' and now I know what was wrong! I need to use `python` to go to 'Python Interpreter', same as `MG5_aMC>` in Madgraph and then it is working.
In that sense, I've run and worked in a Python program before, but surely not very familiar with terminology! 
In this regard, I would suggest, if you just add one more step in your manual, before `import flavio` ,like (`python` or `python3`), that will be very helpful for ignorant Python users like me. Just a thought. 
Anyway, thanks for your response. I learned few things for sure.

**Comment by DavidMStraub** [comment]
You can also [read the paper](https://arxiv.org/pdf/1810.08132.pdf).
