### ISSUE TITLE
Read coefficients for meson mixing in SLHA file (SPheno)

### ISSUE THREAD

**Issue by jjonesperez** [flav-io/flavio#12]
Currently SPheno does not give as an SLHA output any Wilson coefficients for meson mixing. When / if implemented, would be good if flavio could use this info too.

**Comment by DavidMStraub** [comment]
Good idea, this should be done. A warning beforehand: the output of vanilla SPheno should not be used with flavio as it uses incompatible conventions, only a version generated with SARAH/FlavorKit. The latter computes Wilson coefficients of a huge number of operators and at present only a small subset (b->sll, b->snunu, and b->sgamma) are used in the interface.

**Comment by jjonesperez** [comment]
I agree.

On the other hand, on your example SPheno.spc.MSSM file, one notices that SPheno does not output correctly the FLHA format. For example, the first column of FWCOEF should have 8 digits, and one can see it has 7. This is due to an extra "space" in the SPheno code.

Does flavio deal with this? For some coefficients I get:
```
Wilson coefficient (305121, 4141) unknown to flavio; ignored.
Wilson coefficient (305121, 4241) unknown to flavio; ignored.
Wilson coefficient (305141, 4141) unknown to flavio; ignored.
Wilson coefficient (305141, 4241) unknown to flavio; ignored.
Wilson coefficient (305161, 4141) unknown to flavio; ignored.
Wilson coefficient (305161, 4241) unknown to flavio; ignored.
Wilson coefficient (305121, 4142) unknown to flavio; ignored.
Wilson coefficient (305121, 4242) unknown to flavio; ignored.
Wilson coefficient (305141, 4142) unknown to flavio; ignored.
Wilson coefficient (305141, 4242) unknown to flavio; ignored.
Wilson coefficient (305161, 4142) unknown to flavio; ignored.
Wilson coefficient (305161, 4242) unknown to flavio; ignored.
```
but others apparently are read correctly.

**Comment by DavidMStraub** [comment]
The spaces shouldn't matter, but the ones that are ignored are the b->snunu coefficients; there is no reason to ignore them in fact. The historical reason is that these processes have been added after FLHA support was implemented. I will add them.

**Comment by DavidMStraub** [comment]
Oh, you're right. This is apparently a Flavor Kit bug.

**Comment by jjonesperez** [comment]
It is. :-) I've already told Avelino. If everything works out, I'll send you a new SPheno.scp.MSSM file in some hours which should have the complete coefficients with the proper output.
