### ISSUE TITLE
Participate in iminuit v2.0 beta?

### ISSUE THREAD

**Issue by HDembinski** [flav-io/flavio#125]
Dear flavio team,

I am about to finish a major rewrite of iminuit, version 2.0, that replaces Cython as the tool to wrap C++ Minuit2 with pybind11, which is going to solve several issues that the legacy code had. All the good things that this will bring are listed on top of this PR:
scikit-hep/iminuit#502

Switching to the new version of iminuit should be completely transparent to you, since the new version passes the comprehensive suite of unit tests of iminuit-v1.x. However, I would like to use this opportunity to finally remove interface that has been successively marked as deprecated in versions 1.3 to 1.5.

Therefore my two question to you:

* Did you take note of the deprecation warnings in iminuit and did you keep up with the interface changes so far?
* Are you interested in trying out a Beta release of v2.0 to work out any possible bugs in the new version before the release?

Best regards,
Hans, iminuit maintainer

**Comment by peterstangl** [comment]
@HDembinski thank you very much for your message!

- As far as I see, the way iminuit is used in flavio does not produce any deprecation warnings.

  Concerning the interface changes, I just noticed that `Minuit.from_array_func` was introduced in version 1.3. At the moment, flavio still uses a function wrapper for array functions. So we did not fully keep up with the interface changes, but I now plan to remove the old function wrapper soon in favor of using `Minuit.from_array_func`.
- Yes, I can certainly try out the Beta release of v2.0. Is it possible to install it from PyPi or is it necessary to do a development setup?

**Comment by HDembinski** [comment]
Hi @peterstangl if you have to make changes to your code anyway, you may want to hold back on that and perhaps wait for v2.0?

**Comment by peterstangl** [comment]
Yes, that's a good point. There is no hurry to make these changes and I will wait for iminuit v2.0.

**Comment by HDembinski** [comment]
iminuit v2.0 is released, the breaking changes in the interface are documented in the [changelog](https://iminuit.readthedocs.io/en/stable/changelog.html) which can serve as an upgrade guide.

**Comment by peterstangl** [comment]
Thank you @HDembinski! The flavio code has been adjusted to iminuit v2 in PR #130.
