### ISSUE TITLE
Problem with likelihood_contour

### ISSUE THREAD

**Issue by dlanci** [flav-io/flavio#129]
@peterstangl @DavidMStraub 

Hi,

I'm trying to convert the example notebook in 

https://github.com/flav-io/flavio-examples/blob/master/FastFit_WilsonCoefficients_C7p.ipynb

to the new FastLikelihood instances of flavio 2.
I built the FastLikelihood and called the make_measurement() method.

And with 
par = flavio.default_parameters.get_central_all() 

and 

mywilson = wilson.Wilson({'C7p_bs': 2e-6+1j*1e-6},
                         scale=4.8, eft='WET', basis='flavio')
I can run: 

global_fastfit.log_likelihood(par, mywilson)

Obtanining a number.

Now I'm stuck when running:

flavio.plots.likelihood_contour(global_fastfit.log_likelihood,
                                -x_max, x_max, -x_max, x_max, n_sigma=(1, 2), col=0,
                                interpolation_factor=10, steps=30, label='global')

On the docstring it says log_likelihood must be a function but the log_likelihood method of FastLikelihood returns a float that clearly is not callable.

What should I pass as a first argument to flavio.plots.likelihood_contour? In case do you have a flavio 1.6 or greater version of the example notebooks?

Thanks,
Davide

**Comment by peterstangl** [comment]
@dlanci you have to define a function that takes a list of two values as an argument and returns a log-likelihood. For example, if you want to make a plot in the space of Re(C7p) and Im(C7p), you would define something like
```python
par = flavio.parameters.default_parameters.get_central_all()

def ReC7p_ImC7p_function(x):
    Re_C7p, Im_C7p = x
    w = wilson.Wilson({'C7_bs': Re_C7p + 1j * Im_C7p},
                      scale=4.8, eft='WET', basis='flavio')
    return global_fastfit.log_likelihood(par, w)
```
And then `ReC7p_ImC7p_function` is a function that you can pass to `flavio.plots.likelihood_contour`.

You can find recent example notebooks here: https://github.com/peterstangl/flavio-lecture

**Comment by dlanci** [comment]
Thank you so much for the quick answer! It works
