### ISSUE TITLE
Addition of new measurements

### ISSUE THREAD

**Issue by dlanci** [flav-io/flavio#135]
Dear Peter,

I'm trying to add a new measurement to the list available in the measurements.yml file, namely the `LHCb CMS Bs->mumu combination 2014` [link](https://lhcbproject.web.cern.ch/Publications/LHCbProjectPublic/LHCb-PAPER-2014-049.html)

On the [dedicated documentation page](https://flav-io.github.io/docs/add-observable.html) I couldn't find a description of the parameters that need to be passed to the measurement entry, in particular is xi the error on the best fit value for a DLL contour plot? If yes, why is it set to `xi:
    - [0.0, 1.0e-08]
    - [0.0, 1.0e-09]`  for `LHCb Bs->mumu 2017`?
    
Thanks,
Davide

**Comment by peterstangl** [comment]
@dlanci, `xi` stands for x_i, where i runs from 1 to N and N is the number of parameters of the experimental likelihood (e.g. `Bd->mumu` and `Bs->mumu` are the two parameters in your case and the `xi` values are the coordinates in the `Bd->mumu`-`Bs->mumu` plane at which the experimental likelihood `y` is given).
For a more detailed explanation, see the [documentation discussing probability distributions in flavio](https://flav-io.github.io/docs/probability.html) and the [API documentation of multivariate numerical distributions](https://flav-io.github.io/apidoc/flavio/statistics/probability.m.html#flavio.statistics.probability.MultivariateNumericalDistribution).

**Comment by dlanci** [comment]
Thanks a lot!
