### ISSUE TITLE
NP Wilson Coefficients in Various EFTs

### ISSUE THREAD

**Issue by mbr-phys** [flav-io/flavio#136]
Hi, 

I have been working on a project where so far we have two separate fits in flavio: one using the WET for flavour observables and another using SMEFT for Higgs signal strengths. So far we have not seen a way to combine the two sets of observables into a single fit due to the two different EFTs being used for the different Wilson coefficients. 
Is it possible in flavio to introduce Wilson coefficients in two separate EFTs like this into one FastLikelihood fit?

Thanks, Matthew

**Comment by peterstangl** [comment]
Hi Matthew,

no it's not possible to construct a FastLikelihood in two separate EFTs and it would be inconsistent to do something like this. The WET Wilson coefficients encode some of the *same* new physics effects as the SMEFT Wilson coefficients. Contributions to WET Wilson coefficients are generated from SMEFT Wilson coefficients by matching the two EFTs at the electroweak scale.
So if you want to consider observables at the electroweak scale (like Higgs signal strengths), you should use SMEFT anyway. RG running and matching is performed automatically by flavio (using the `wilson` package in the background) such that it is straight forward to constrain SMEFT coefficients using also flavour observables.
If you need a likelihood for flavour and Higgs, it is actually not necessary to construct this yourself using `flavio`. You can simply use the Python package `smelli` that builds upon `flavio` and implements a likelihood in the space of SMEFT Wilson coefficients taking into account flavour and Higgs observables (and many more): https://github.com/smelli/smelli
For a recent short intro to `smelli`, see https://arxiv.org/abs/2012.12211

**Comment by mbr-phys** [comment]
Hi, Peter, 

That all makes a lot of sense, and `smelli` seems exactly what I am looking for.

Thanks!

**Comment by DavidMStraub** [comment]
Looks like we need to advertise smelli more strongly on the flavio website :wink:

**Comment by peterstangl** [comment]
> Looks like we need to advertise smelli more strongly on the flavio website wink

That's a very good point! I think at the moment smelli is not mentioned at all on the flavio website.

**Comment by peterstangl** [comment]
I think this issue can be closed.
