### ISSUE TITLE
Possible bug in flavio.plots.band_plot

### ISSUE THREAD

**Issue by tblake00** [flav-io/flavio#14]
Should there be a factor a factor of two in the definition of f_vect(x, y) at:
https://github.com/flav-io/flavio/blob/master/flavio/plots/plotfunctions.py#L132
to convert the Delta log likelihood to a Delta chi^2?

**Comment by DavidMStraub** [comment]
You're right, thanks! I fixed it (bb660ee84140da41b3d79e79e8a06733c9aae58f) and renamed some variables to be less ambiguous. I'll add some doc strings to this file and then make a bugfix release.

**Comment by DavidMStraub** [comment]
Sorry, factor of 2 went the wrong way ... now correct in 731b9673e76dd7cec38a7e930afbcd957f6d5d67
