### ISSUE TITLE
Implementation of BR(Bs→phi gamma) measurement

### ISSUE THREAD

**Issue by MartinoBorsato** [flav-io/flavio#145]
Dear flavio maintainers,

I noticed the LHCb measurement of BR(Bs->phigamma) is often misused to constrain C7 Wilson coefficients along with B-factory measurements of BR(B0->K*gamma) and BR(B->Xsgamma). However, [LHCb only measured the ratio BR(Bs->phigamma)/BR(B0->K*gamma)](https://inspirehep.net/literature/1184178) and then used the B-factories measurement of BR(B0->K*gamma) to get BR(Bs->phigamma). The Wilson coefficient C7 enters the two modes in the same way and therefore the LHCb measurement is not sensitive to NP contributions to C7. 

I think a new observable for the ratio BR(Bs->phigamma)/BR(B0->K*gamma) should be implemented. Then, the  LHCb measurement reported in `measurements.yaml` should be for the value of this ratio R=1.23±0.06 (stat.)±0.04 (syst.)±0.10(fs/fd).

I hope this is useful,
Martino

**Comment by DavidMStraub** [comment]
Hi Martino,

you are absolutely right, thanks for reporting this.
@peterstangl, this variable should then also be used in `smelli` in place of the BR, since currently the two observables are treated as independent.

**Comment by peterstangl** [comment]
Thank you Martino!

I have implemented your suggestion in PR  #146. For `±0.10(fs/fd)` I used `±0.03` given that arXiv:1209.0313 quotes `fs/fd= 0.267+0.021−0.020`.

**Comment by MartinoBorsato** [comment]
Thanks a lot @DavidMStraub and @peterstangl for the very quick reply!
I think there's a misunderstanding about fs/fd: what I meant by `±0.10(fs/fd)` is that there's a 0.10 uncertainty related to the uncertainty on fs/fd, not that 0.10 should be multiplied by fs/fd (sorry my notation was ambigous). 
The value of the BR ratio should read `1.23 ± 0.06 ± 0.04 ± 0.10` as in the [paper](https://inspirehep.net/literature/1184178).

Actually, we could decide to use a more precise value of fs/fd from [this paper](https://cds.cern.ch/record/1559262/files/LHCb-CONF-2013-011.pdf) that came out after the Bs->phigamma paper. Then the experimental measurement of the BR ratio should read `1.19 ± 0.06 ± 0.04 ± 0.07`.

**Comment by peterstangl** [comment]
Thank you for the clarification @MartinoBorsato, this makes much more sense than what I did!

I have implemented the updated result based on the more precise value of fs/fd in commit https://github.com/flav-io/flavio/pull/146/commits/a9e15c140d525b4c29def67b84c2270bc374f701.

**Comment by MartinoBorsato** [comment]
Perfect, thanks a lot

**Comment by peterstangl** [comment]
This is now included in the new flavio version 2.2.0.
