### ISSUE TITLE
Fit for combinations of Wilson Coefficients

### ISSUE THREAD

**Issue by dlanci** [flav-io/flavio#153]
Hi,

I'd like to perform a fit to the sum/difference of two Wilson Coefficients provided in the 'flavio' basis, how can I realise this? 

Say that I'd want to fit for C^{S}_{bsmumu} - C^{Sp}_{bsmumu}. I had a go with the following code, without success:

```python
def FLL(x):
   
     Re_Cs_sum=x[0]
     w = Wilson({
              
                'CS_bsmumu': Re_Cs_sum, 
                
               },
                    scale=4.8,
                    eft='WET', basis='flavio')
    return L.log_likelihood(par, w)

def chi2(xy, L):
    
      Re_Cs=xy[0]
      Re_Csp=xy[1]
      x_in =[(Re_Cs-Re_Csp)/2]
      return -2*FLL(x_in)

```
How could I edit it to achieve what I need?

Thanks

**Comment by DavidMStraub** [comment]
```python
# ...
C_sum, C_diff = xy
Cs = (C_sum + C_diff) / 2
Csp = (C_sum - C_diff) / 2
wc_dict = {"CS_bsmumu": Cs, "CSp_bsmumu": Csp}
# ...
```

Does this work?

**Comment by dlanci** [comment]
I'm not sure if this is exactly what I want, to put it in code I'd like to have:

```python
# ...
C_diff=x
wc_dict = {"CS_bsmumu-CSp_bsmumu":C_diff}
# ...
```

Thus reducing the dof to 1 for the CS_bsmumu. And with your solution I'd still have 2dof in the Likelihood

**Comment by dlanci** [comment]
Sorry for bothering my bad. I now did:

```python
C_sum, C_diff = xy
C_sum=0.
Cs=(C_sum + C_diff)/2.
Csp=(C_sum - C_diff)/2.
wc_dict = {"CS_bsmumu": Cs, "CSp_bsmumu": Csp}
```

And checked that the resulting likelihood function doesn't depend on the value at which I set C_sum, which is what I wanted to test. 

Thanks!
Davide
