### ISSUE TITLE
Obtaining best fit values for a n-dimensional fit

### ISSUE THREAD

**Issue by SueGua** [flav-io/flavio#154]
Hello there,

I was wondering how to get  the best fit value for the following example (which I do not know if it is well defined for more than 2 WCs):

fit3d = FastLikelihood(name ='3d FastLikelihood',
                       observables = observables,
                       include_measurements = measurements)

fit3d.make_measurement(N=1000, threads=4, force=True)

def FLL(x):
    Re_C9, Re_C10, Re_C9p = x
    par = flavio.default_parameters.get_central_all()
    wc = Wilson({'C9_bsmumu': Re_C9, 'C10_bsmumu': Re_C10, 'C9_bsmumu': Re_C9p, },
                scale=4.8,
                eft='WET', basis='flavio')
    return fit3d.log_likelihood(par, wc)

and then with that I would like to get the "best fit" values for the WCs in a similar way like with the old method 'best_fit':

fit3d.best_fit()

I appreciate any help.

**Comment by DavidMStraub** [comment]
Hi,

you can use any optimization tool you like. I recommend [iminuit](https://iminuit.readthedocs.io/en/stable/), it's great.

**Comment by SueGua** [comment]
Wow, as easy as 

from iminuit import minimize

%time minimize(FLL,(0, 0, 0))

CPU times: user 2min 11s, sys: 17.5 s, total: 2min 29s
Wall time: 51.7 s
      fun: -260.97071505655987
 hess_inv: [[ 1.81024744e-02  1.09116252e-04 -4.85322618e-05]
 [ 1.09116252e-04  1.79621434e-02 -3.85834639e-05]
 [-4.85322618e-05 -3.85834639e-05  2.97150058e-04]]
  message: 'Optimization terminated successfully.'
     nfev: 102
     njev: 0
  success: True
        x: array([-1.15991814,  0.13684068,  0.57998515])

Thanks so much!
