### ISSUE TITLE
Factor 2 in the upper limit for Br(B0->Knunu)?

### ISSUE THREAD

**Issue by bednya** [flav-io/flavio#165]
Hi,

I was comparing the upper limits in measurements.yaml with Belle'2017 measurments 

and found that BR(B0->Knunu) upper limit here 
https://github.com/flav-io/flavio/blob/ef88a933d09f008c392e6f1823850ecbf80aa726/flavio/data/measurements.yml#L4949
is a factor 2 larger than given in Table 2 (2 row, 3 column):
https://journals.aps.org/prd/pdf/10.1103/PhysRevD.97.099902

Any special reason for this or it is just a misprint?

**Comment by DavidMStraub** [comment]
Belle only measures Kshort. They are missing the other half. The theoretical calcuation contains both.

**Comment by DavidMStraub** [comment]
(I mean, *could* measure. Obviously, they are not measuring anything yet.)

**Comment by bednya** [comment]
David, thanks a lot for the clarification!
