### ISSUE TITLE
fK form factor correlation with fpi

### ISSUE THREAD

**Issue by MJKirk** [flav-io/flavio#171]
It's not clear to me where the flavio value of the correlation between `f_K` and `f_pi` comes from.
Reading the comments in
https://github.com/flav-io/flavio/blob/3b8032913b79d01a48190ca7ab3366ff67b70173/flavio/data/parameters_correlated.yml#L26-L41
it suggests it comes from FLAG, but I can't see that value in the review.
Alternatively if it comes from reverse engineering it to reproduce the ratio `f_K/f_pi` as suggested by @DavidMStraub's earlier commit (https://github.com/flav-io/flavio/commit/0f75d69eed5746b8d939a0140755f40a1b20dbbd), then it seems to me that both the error on `f_K` and the correlation between `f_K` and `f_pi` are not known, and there is a whole range of values for both that would reproduce the FLAG error on the ratio.
E.g `f_K = 0.1554(8)` and a correlation of `0.975` would also reproduce the ratio correctly.

**Comment by DavidMStraub** [comment]
Which is the value you can't see in the review? From table 1:

<img width="540" alt="grafik" src="https://user-images.githubusercontent.com/10965193/143603334-8e9afe51-40bb-4b09-b39c-b2125f83a754.png">

**Comment by MJKirk** [comment]
The correlation coefficient between fK and fpi.
I'm saying it seems like you took fK/fpi and fpi from FLAG, and then reverse engineered **both** fK and the correlation between fK and fpi. But I don't see how there is enough information for that. Unless the correlation is already known

**Comment by DavidMStraub** [comment]
I see your point. The central value for fK obviously comes from the ratio, but the correlation can only be extracted if the uncertainty on fK is known, and there is no reference given for that. No idea where it came from. But I suspect there was a perfectly well thought through & legitimate reasoning behind it :thinking: 

What's clear is that the 0.3 MeV error (2+1+1) is not applicable as it uses the experimental value of fpi to set the lattice scale.

**Comment by MJKirk** [comment]
Okay, glad I have not missed something.
It appears from some quick calculations that if you just take both the uncertainty and the correlation as free parameters, then that particular value for the fK uncertainty minimises the correlation you need to reproduce fK/fpi. So maybe 2019 David thought that was a good reason?

**Comment by DavidMStraub** [comment]
Fortunately 2019 David didn't throw away his data.

I found the notebook: https://gist.github.com/DavidMStraub/813bd0c4296837936a188a29c8d8b981

Apparently, what he assumed is that fpi and the ratio fpi/fK are fully *un*correlated. Is that justified? No idea.

Btw all of this was part of a detailed numerical comparison of K and beta decay predictions with Martin G-A & Adam F for an awesome paper that unfortunately was never finished.

**Comment by MJKirk** [comment]
:clap: and a :medal_sports: to 2019 David.
Naively, since FLAG does not mention any correlation between fpi and fK/fpi I would think it is reasonable to assume there isn't one, and therefore your method is fine. Maybe something to ask next time I see some lattice person...

Does any of this work live on in https://arxiv.org/abs/2010.13797? I guess/hope you don't check the arXiv much these days.
The whole beta vs K decays and Vus/Vud stuff is something I have been working on, and specifically why I was looking at this - to be able to change these parameters.

**Comment by MJKirk** [comment]
Anyway, thanks for digging this out!
Actually, another general history question - is there some reason you didn't choose to just use fpi and fK/fpi straight as the inputs to flavio, and then do `fK/fpi * fpi` everywhere as needed?

**Comment by DavidMStraub** [comment]
> Does any of this work live on in https://arxiv.org/abs/2010.13797

No, not really, but [v2.0](https://github.com/flav-io/flavio/releases/tag/v2.0.0) added most of the observables we considered.

> is there some reason you didn't choose to just use fpi and fK/fpi straight as the inputs to flavio, and then do fK/fpi * fpi everywhere as needed?

I guess it just seemed more natural to treat all decay constants equally as parameters; similarly for the B bag parameters. But it would work just as well with `fK/fpi` and `fpi`.

**Comment by MJKirk** [comment]
Fair enough. Thanks again for the information!
