### ISSUE TITLE
The definition of C["ll_1221"]

### ISSUE THREAD

**Issue by haolinli1991** [flav-io/flavio#174]
https://github.com/flav-io/flavio/blob/3b8032913b79d01a48190ca7ab3366ff67b70173/flavio/physics/zdecays/smeftew.py#L26

I have a question on the above formula, what is the convention for the Larganigan term corresponding to the Oll operator? 
It seems that in this equation you only take into account the independent flavor entry in the Warsaw basis in the Lagrangian without summation over all the flavor indices, otherwise there should not be a 1/2 factor or C["ll_1221"].

However, in the wilson package in the matching between SMEFT and WET (smeft_tree.py) you have the following lines 
    GFx = GF - sqrt(2)/4 * ( -C['ll'][1,0,0,1] - C['ll'][0,1,1,0] + 2*C['phil3'][1,1] + 2*C['phil3'][0,0] )
  where both 1221 and 2112 entries appear, which should be all equal to the input of C["ll_1221"] according to the symmetrization function in the smeftutil.py.

Is there any inconsistency between these two?

**Comment by haolinli1991** [comment]
> The matrix `C['ll']` is in the "redundant flavour basis" in contrast to WCxf coefficients like `C["ll_1221"]`. See appendix A.2 in https://arxiv.org/pdf/1810.07698.pdf.

I know, this is what I expect, my question is that this seems to be inconsistent with the treatment in matching in Wilson.

More specifically, for example,
In a global analysis, I need the flavio to calculate the W decay width, and also some other low energy flavor observables which need the matching between SMEFT and WET. In this case, if I initialize a wilson class with the value of "ll_1221", then in the calculation of the W decay it seems that it adopts the convention for non-redundant basis, while for low energy flavor observables it adopt the redundant flavor basis due to the internal symmetrization procedure and the equation used in the matching.

**Comment by peterstangl** [comment]
Hi @haolinli1991

>both 1221 and 2112 entries appear, which should be all equal to the input of C["ll_1221"] according to the symmetrization function in the smeftutil.py.

This is not the case. In the symmetrized, redundant basis, where both the 1221 and 2112 entries appear, their sum equals the `C["ll_1221"]` coefficient in the non-redundant basis. So `C["ll_1221"]` is 2 times as big as each of the 1221 and 2112 entries in the redundant basis. The appearance of this symmetry factor of 2 in the redundant basis is explained in the reference pointed out above by @DavidMStraub. If you take into account this symmetry factor, then I think there is no inconsistency in the two formulas you quote.

**Comment by peterstangl** [comment]
@haolinli1991, if there should still be something unclear or you think there is some other issue, please comment. Otherwise I will close this issue soon.

**Comment by haolinli1991** [comment]
> @haolinli1991, if there should still be something unclear or you think there is some other issue, please comment. Otherwise I will close this issue soon.

Sorry for the late reply, and thanks very much for your answers. 
Would you mind pointing to me where in the wilson package, you take into account this factor of 2 in the symmetrization? 
In the smeftutil.py  for the older version of wilson (maybe common.py in your new version), the function "symmetrize_4" seems not to take into account such a factor of 2.
I may be totally wrong, as there might be more intermediate process, such that upon the usage of symmetrize_4, the factor of 2 issue has already been taken care of by some previous steps. 

Thanks!

**Comment by peterstangl** [comment]
> Would you mind pointing to me where in the wilson package, you take into account this factor of 2 in the symmetrization? In the smeftutil.py for the older version of wilson (maybe common.py in your new version), the function "symmetrize_4" seems not to take into account such a factor of 2. I may be totally wrong, as there might be more intermediate process, such that upon the usage of symmetrize_4, the factor of 2 issue has already been taken care of by some previous steps.

You are right that the `symmetrize_4` function itself does only the symmetrization but not the normalization. That's why in `symmetrize_nonred`, the result of `symmetrize_4` is divided by the matrix `_d_4`, which contains all the symmetry factors:
https://github.com/wilson-eft/wilson/blob/8931ea52cd8cedab3712a207a9bc02cdaa4e6151/wilson/util/common.py#L955-L956

**Comment by haolinli1991** [comment]
> > Would you mind pointing to me where in the wilson package, you take into account this factor of 2 in the symmetrization? In the smeftutil.py for the older version of wilson (maybe common.py in your new version), the function "symmetrize_4" seems not to take into account such a factor of 2. I may be totally wrong, as there might be more intermediate process, such that upon the usage of symmetrize_4, the factor of 2 issue has already been taken care of by some previous steps.
> 
> You are right that the `symmetrize_4` function itself does only the symmetrization but not the normalization. That's why in `symmetrize_nonred`, the result of `symmetrize_4` is divided by the array `_d_4`, which contains all the symmetry factors: https://github.com/wilson-eft/wilson/blob/8931ea52cd8cedab3712a207a9bc02cdaa4e6151/wilson/util/common.py#L955-L956

Great! Thanks very much for the explanation.
