### ISSUE TITLE
Error: package 'particle' removed the method data.open_text()

### ISSUE THREAD

**Issue by resonweb** [flav-io/flavio#175]
In line 12 of parameters.py, import particle.data as p_data.

In line 232 of parameters.py, using p_data.open_text(), but this method has deprecated in particle-v0.20.0 a few days ago.

Because of this problem, "import flavio" will give an Error and can not be imported. Please fix this bug, thank you.

**Comment by DavidMStraub** [comment]
Thanks for the report!

The [release notes](https://github.com/scikit-hep/particle/releases/tag/v0.20.0) don't even mention that. Quite unfortunate.

**Comment by peterstangl** [comment]
Thank you @resonweb for reporting this issue! The problem has been fixed in PR #176.
