### ISSUE TITLE
Questions regarding proper use of flavio's likelihoods (SPheno - flavio)

### ISSUE THREAD

**Issue by kys-sheng** [flav-io/flavio#187]
Hi,
I have been trying to get a global likelihood based on all possible relevant observables with `SPheno`'s `wcxf` as an input. In this case, I can only work with `WET` and I am unable to use `smelli` for this case since `smelli` works with `SMEFT`. In other words, Im trying to build a bridge between `SPheno` and `flavio` such that I can check the global likelihood of relevant observables with `flavio` using SPheno outputs.

I understand that extreme attention is needed to be given into choosing appropriate observables and experiments as well as using a consistent, reasonable and reliable fast likelihood definition. However, I must admit that I am not too familiar with likelihoods and nuisance parameters other than the basics. As such, I need some help with double checking what I am doing is correct or not.

Whatever follows are based on my understanding on materials I can find online and since I have not attend any flavio talks in person yet, it is highly likely that I might misunderstood the contents. Please correct me if any of the statements I made are erroneous or just plain wrong. 

So far, I have noticed a few details that needs to be taken care of to construct a good `FastLikelihood` with `wcxf` from `SPheno` as an input:
1. Do not include observables that is dependent on WC from SMEFT: 
	- because SPHENO output is already in WET, and WET->SMEFT cant be done

2. Use only relevant parameters for the observables: 
	- Use `get_dependent_parameters_sm` to check which parameters are relevant

3. Do not use overlapping experiments. Ref[1,2]
	- Cases with combinations of experiments should be given attention (choose the combination of experiments once or the experiments separately), as shown in Ref[2] 
	- as mentioned in Ref[1] 
	   > "... can lead to inconsistent results in several cases, e.g: 
	        -including multiple measurements that are not independent of each other"

 
	- Relevant observables with this scenario: `<AFB>(B0->K*mumu)`,` <FL>(B0->K*mumu)`,` <dBR/dq2>(B0->K*mumu)`, `BR(Bs->mumu)`,` BR(B0->mumu)`, `a_mu`

4. Must consider all other observables of an experiment result if it contains multiple observables, Ref [1,2]:
	- as shown in Ref [2]
	- most experiments (though not all) contains multiple observables (if any of it is left out, a warning will come out)
	
5. *Check either:
      A.  *Theory uncertainties are negligible (Case 1 of ref[3]):
          - I guess one way to do this is to compare `np_uncertainty() `vs `get_1d_errors_random()` for every possible observables? 
          - Although I am not sure what is a good definition of negligible.
          
    or :    

      B. *Theoretical uncertainties in the presence of new physics are more or less equal to the ones in the SM (`FastLikelihood` in APIdoc and Case 2 of ref[3]):
          - I am not sure how to check this consistently 

8. *Do not use experimental results with distribution of :
	- `asymmetric_normal` 		        : (Because its asymmetric, not a good approximation for normal/gaussian)**
	- `general_gamma_upper_limit` 	: (Because its not normal/gaussian)
	- `gamma_upper_limit` 		        : (Because its not normal/gaussian)
	
*I am highly doubtful of whether what I understand/what I am doing is correct and your input is highly appreciated and crucial. 
**An alternative would be to use sigma^2 vai the alternative formulations from https://en.wikipedia.org/wiki/Split_normal_distribution	

Additional questions:
1. It is mentioned in ref[1]:
    > "... can lead to inconsistent results in several cases, e.g: ...
    >   ...including constraints on parameters that come from measurements included in
    > the likelihood (e.g. the default constraint on Vub that comes from B → π`ν),"

    Is there a consistent way of double checking this?

2. Is there anything else that I have missed out that is very important before proceeding?

Many thanks in advanced and hope to hear from you soon!

Reference:
[1] flavio paper : https://arxiv.org/pdf/1810.08132.pdf 
	– including multiple measurements that are not independent of each other.
[2] Peter Stangl's tutorial : https://github.com/peterstangl/flavio-lecture/blob/master/4%20Likelihoods.ipynb
[3] Peter Stangl's talk : https://indico.cern.ch/event/1011800/contributions/4245824/attachments/2224349/3767163/Stangl_21-04_EFT_fits.pdf
[4] David M. Straub's talk : https://indico.cern.ch/event/787665/contributions/3374415/attachments/1861971/3060407/straub-smefttools-2019.pdf

**Comment by DavidMStraub** [comment]
Hi, short answer:
```python
smelli.GlobalLikelihood(eft="WET")
```

**Comment by kys-sheng** [comment]
I have no idea how I'd missed this!
Thanks!
