### ISSUE TITLE
Unable to use <AFB>(B0->Kmumu), and similar binned observables

### ISSUE THREAD

**Issue by N-Dakshesh** [flav-io/flavio#193]
Hi,
When trying to use the likelihood method with <AFB>(B0->K*mumu), I get the error 'no measurements found'. The measurements.yml file definitely contains these, and theoretical methods work such as np_prediction, but it's impossible to get the likelihood. Is this a problem with q2 inputs, since they are binned? I can't find how to pass through q2min and q2max.

**Comment by DegCo** [comment]
Hi, 
May I know how you solved this problem? I am confident that it can be done with the appropriate syntax, but I don't see a way from the tutorials.. Thank you!
