### ISSUE TITLE
Log likelihood always returns the same value - Wilson problem

### ISSUE THREAD

**Issue by N-Dakshesh** [flav-io/flavio#194]
Hi,
I'm looking to use the log likelihood method to fit Wilson coefficients to our measurement data. I plan to use an external minimiser.

The problem is, if I change the Wilson coefficients, it doesn't change the likelihood (I change in w).

Also, I can't find what C9_sdmumu actually means (i've used it since I'm interested in C9, C10 for B0 -> K*mumu decay, and K* has a strange and down quark), but this is just a guess.

w = Wilson({ 'C9_sdmumu': 0, 'C10_sdmumu': 1}, scale=160, eft='WET', basis='flavio')

par = flavio.default_parameters
par_dict = par.get_central_all()

llh = Likelihood (fit_parameters = ['B0->K*0 deltaC9 a_+ Re', 'B0->K*0 deltaC10 a_+ Re'], observables =[('<AFB>(B0->K*mumu)',0.1,0.98), ('<FL>(B0->K*mumu)',0.1,0.98)])

llh.log_likelihood(par_dict, w)

**Comment by DavidMStraub** [comment]
Read the paper and the basis documentation please: https://wcxf.github.io/

Switching on a s->d Wilson coefficient and expecting a b->s transition to show an effect, well...
