### ISSUE TITLE
absolute chi2 value

### ISSUE THREAD

**Issue by girishky** [flav-io/flavio#195]
Issue #134 discusses how to obtain pull in units of sigma using ```flavio.statistics.functions.pull``` which requires difference of chi2 value, calculable as  [-2*(FLL(NP)-FLL(SM)], and relevant dof. I was wondering how to obtain absolute chi2 value in the SM. (The quantity  -2*FL(SM) turn out to be a negative number so it is not absolute chi2).  Let me know if I should provide a MWE to illustrate my issue.
Thanks.

**Comment by DavidMStraub** [comment]
Twice the negative log likelihood and &chi;² can differ by constants, e.g. for a 1D normal distribution by ln(&sigma;(2&pi;)<sup>1/2</sup>).

**Comment by girishky** [comment]
OK..I see. The LL function has a factor $(2\pi \sigma^2)^{-n/2}$ multiplying `exp` function. Thanks...but isn't the constant you mentioned is  $2n \ln[\sigma (2\pi)^{1/2}]$ (n=1 for 1D dist.) ?

**Comment by DavidMStraub** [comment]
Oh, perhaps I misunderstood your question. I wanted to point out that you don't need the absolute chi^2 to compute the pull, but probably this is not what you asked.

Perhaps you can have a look at appendix B of https://arxiv.org/pdf/1903.10434.pdf and see if that is helpful.

**Comment by girishky** [comment]
Thanks, David...I will have look. Yes, my query was about calculating $\chi^2$ (e.g. in table 3 of your paper).

**Comment by peterstangl** [comment]
If you want to obtain a total $\chi^2$ that is zero in the case where all theory predictions are equal to the experimental measurements, you should be able to get this by setting  `delta=True` in the arguments of the `log_likelihood` method.

**Comment by girishky** [comment]
thanks @peterstangl. I think this is what I was looking for.
