### ISSUE TITLE
Calculation of SM Wilson Coefficients

### ISSUE THREAD

**Issue by Trifis** [flav-io/flavio#22]
Could you please clarify, which are the parameters of the method flavio.physics.running.running.get_wilson()
I want to calculate the SM Coefficient e.g. C9p_bsee from the electroweak scale down to the mass of the B meson. How one does this?

Thanks in advance.

**Comment by DavidMStraub** [comment]
`C9p_bsee` vanishes in the SM at any scale. If you are interested in the running of the NP contribution, it is easier to use the `flavio.WilsonCoefficient()` class and its `get_wc` method:

```python
wc = flavio.WilsonCoefficients()
wc.set_initial({ 'C9p_bsee': 1.5 }, scale=160)
par = flavio.default_parameters.get_central_all() # parameter dictionary
wc.get_wc(sector='bsee', scale=4.8, par=par, nf_out=5)
```

The `get_wilson` function is more low-level as it requires the manual specification of the anomalous dimensions.

Admittedly though, both functions are poorly documented and this must be improved.

**Comment by Trifis** [comment]
I am sorry I meant, of course the left-handend SM current, namely C9_bsee, but I think the implementation is going to be exactly the same, am I right? You set the experimental value of C9 at the electroweak scale (is this already documented into a parameter dictionary?) and then you choose the new scale as an argument of get_wc.

**Comment by DavidMStraub** [comment]
The SM contributions to the b->s WCs are currently included in poorly documented functions as most methods (e.g. `np_prediction`) work with `WilsonCoefficient` objects that contain only NP contributions.

For C9, you can look at the `function flavio.physics.bdecays.wilsoncoefficients.wctot_dict`, used like

```python
wc = flavio.WilsonCoefficients() # SM-only
par = flavio.default_parameters.get_central_all()
flavio.physics.bdecays.wilsoncoefficients.wctot_dict(
    wc_obj=wc, sector='bsee', scale=4.8, par=par, nf_out=5)
```

Looking at the [source of this function](https://github.com/flav-io/flavio/blob/master/flavio/physics/bdecays/wilsoncoefficients.py#L52-L77), you also have a usage example for `get_wc`.

**Comment by Trifis** [comment]
Ok, this works like charm. But, I have some remarks. In the source of `wtot_dict`, there is by default input of 120GeV for the higher energy scale in the function `get_wilson`. Is this the point, at which the SM WC initial values are set? Is there a way to check the exact implementation of the running? The problem is that using a code that uses the implementation of arxiv:hep-ph/9501281v1, there is a deviation in C10 (-3.96 as opposed to -4.18 of flavio).

**Comment by DavidMStraub** [comment]
The high-scale values of the SM Wilson coefficients are currently hard-coded. They contain NNLO QCD and NLO EW corrections. But note that C10 doesn't renormalize under QCD, so the difference should be of O(alpha_em) and thus tiny. The numerical state of the art for C10 is discussed in https://arxiv.org/pdf/1311.0903.pdf.

**Comment by Trifis** [comment]
Thanks, I shall study the reference.
