### ISSUE TITLE
Missing obs_err_dict in flavio.plots.q2_plot_th_bin

### ISSUE THREAD

**Issue by f-thiele** [flav-io/flavio#24]
Hi all,

I noticed that calling `flavio.plots.q2_plot_th_bin` in [flavio.plots](https://github.com/flav-io/flavio/blob/master/flavio/plots/plotfunctions.py#L146) with wilson coefficients defined - so `wc!=None` - it will always result in a crash since `obs_err_dict` does not exist for assigning

```python
err = obs_err_dict[bin_]
```

four lines later. Is there any way of fixing this by pulling up uncertainties, or does there maybe even exist an equivalent to `flavio.sm_uncertainty` for new physics?

Best,

Fabian

**Comment by DavidMStraub** [comment]
Hi,

good point. Actually I had this function (`np_uncertainty`) "lying around" anyway. Can you check if the last two commits to master solve your problem?

Thanks, D.

**Comment by f-thiele** [comment]
Hi David,

thanks for your quick response. Your commits do indeed solve it and things are running smooth now.

Best,

Fabian
