### ISSUE TITLE
PyPI Password-based uploads disabled

### ISSUE THREAD

**Issue by peterstangl** [flav-io/flavio#256]
The current GitHub workflow for publishing flavio on PyPI produces the error

> Password-based uploads disabled
As of 2024, PyPI requires all users to enable Two-Factor Authentication. This consequently requires all users to switch to either Trusted Publishers (preferred) or API tokens for package uploads. Read more: https://blog.pypi.org/posts/2023-05-25-securing-pypi-with-2fa/

@DavidMStraub unfortunately my PyPI account is blocked because I can't verify my primary email address (to which I don't have access anymore) and having a verified secondary email address somehow doesn't help. So at the moment I cannot switch to Trusted Publishers or API tokens. Could you please add my new account `pstangl` (https://pypi.org/user/pstangl/) as `flavio` (and also `smelli`) maintainer?

**Comment by DavidMStraub** [comment]
Done. I'm afraid requests that require human interaction can take eons on PyPI (even longer than Github :wink:)

**Comment by peterstangl** [comment]
Thanks a lot! :)
The workflow has been fixed and v2.6.0 has been released on PyPI.
