### ISSUE TITLE
correct parameter set needs to be passed for conjugation of parameters

### ISSUE THREAD

**Issue by talismanbrandi** [flav-io/flavio#32]
The parameter set passed in line 31 of flavio/physics/bdecays/bvll/nonfactorizable.py:

return flavio.physics.bdecays.bvll.qcdf.helicity_amps_qcdf(q2, wc, par_dict, B, V)

should be par and not par_dict since par is correctly conjugated and not par_dict.

**Comment by DavidMStraub** [comment]
Thanks!
