### ISSUE TITLE
Problem with observables included in "Pseudo-measurement"

### ISSUE THREAD

**Issue by peterstangl** [flav-io/flavio#33]
When performing several fits with different combinations of observables, a wrong Warning occurs when one first defines e.g. a global fit and then fits for individual observables. The reason for this is the pseudo-measurement added to the list of measurements by defining the global fit. This pseudo-measurement includes all the observables and thus also constraints all the observables.
Afterwards, trying to fit an individual observable results in the Warning
```python
("{} of the measurements in the fit '{}' "
"constrain both '{}' and '{}', but only the "
"latter is included among the fit "
"observables. This can lead to inconsistent "
"results as the former is profiled over."
).format(count, self.name, obs1, obs2))
```
Explicitly specifying the measurements with `include_measurement` avoids this problem by not including the pseudo-measurements.

**Comment by DavidMStraub** [comment]
Fixed by #34.
