### ISSUE TITLE
Obervables and relevant NP operators

### ISSUE THREAD

**Issue by Trifis** [flav-io/flavio#43]
Is there a way to check which NP operators contribute to each observable? For example, is there a method to check which operators are relevant to an observable, such as 'BR(B0->K*nunu)'. Also, is the reverse also possible? i.e. to have a list of all observables a NP operator would affect. 
Finally, is flavio considering only tree-level NP contributions or also loop effects generated by the NP operators?

Looking forward to your reply.

**Comment by DavidMStraub** [comment]
Hi @Trifis,

there is no function at the moment to do what you want (although it wouldn't be hard to hack one I guess). In practice, if you want to find out which operators contribute without looking at the source code, the best starting point in the [WCxf basis file](https://wcxf.github.io/assets/pdf/WET.flavio.pdf). The operators in in each "sector" in [WCxf](https://wcxf.github.io/) do not mix with other operators under QCD or QED. Thus you are guaranteed that only operators from a single sector contribute to a given low-energy observables. In the case of B->K*nunu, the relevant sector is `sbnunu`. You can see there are 18 operators. All of them contribute to this process.

Concerning loop contributions: do you mean insertion of local operators in SM loops? The only case where this used to be implemented was four-quark operator matrix elements in b->sll, but it was [recently removed](https://github.com/flav-io/flavio/releases/tag/v0.25) when changing the operator basis and will be added back soon. Which process are you thinking of?

**Comment by Trifis** [comment]
_Thus you are guaranteed that only operators from a single sector contribute to a given low-energy observable._

Thank you very much for the reply. I think the above says it all. 

What I had in mind is for example, a leptoquark coupling inducing some contribution to e.g. B-Bbar mixing via a box. It is reassuring to know, that those contributions, have to be put in explicitely by hand as extra terms in the NP WC.

**Comment by DavidMStraub** [comment]
This is a very old issue, but I just added a feature that at least goes into this direction. The next release will contain a function `flavio.functions.get_dependent_wcs` which will return the WCxf EFT, basis, sector and scale of the Wilson coefficients relevant for any observable. For instance,
```python3
import flavio
flavio.functions.get_dependent_wcs('eps_K')
% will return
{(2.0, 'WET-3', 'flavio', ('sdsd',))}
```

More fine-grained information (i.e. which specific WCs are relevant) will not be possible unfortunately, so I think this issue can be closed.
