### ISSUE TITLE
Plotting produces warnings if no font named "Computer Modern Roman" is present

### ISSUE THREAD

**Issue by peterstangl** [flav-io/flavio#44]
https://github.com/flav-io/flavio/blob/409c522dce62fecc61685d85c4ac3489e79cab45/flavio/plots/config.py#L6

The above line can lead to multiple warnings during plotting if no font called "Computer Modern Roman" is installed. This might for example happen if Computer Modern Unicode (CMU) fonts are installed that use a different naming scheme such that Computer Modern Roman is called "cmu serif". Or of course if Computer Modern Roman is not installed at all and other fonts like DejaVu are used as default fonts.

I would suggest to change this line to
```python
rc('font',**{'family':'serif',
             'serif':['Computer Modern Roman','cmu serif']+rcParams['font.serif']})
```
This would set the first serif font to try to 'Computer Modern Roman', the second one to 'cmu serif' and keep all other serif fonts in the list such that they are used if the first two are not found.

**Comment by DavidMStraub** [comment]
Fixed by #45.
