### ISSUE TITLE
Slow multi-thread calculation of SM covariance for fit with SMEFT WCs

### ISSUE THREAD

**Issue by peterstangl** [flav-io/flavio#46]
After defining a `FastFit` instance `fit` with SMEFT WCs, calling
```python
fit.get_sm_covariance()
```
is considerably faster than the parallelized version
```python
fit.get_sm_covariance(threads=4)
```

This seems to be due to the fact that the single thread version calls `self.get_predictions_array`
with arguments `par=False, nuisance=True, wc=False`,
https://github.com/flav-io/flavio/blob/9a6b071d9f88362dffdbdfd5faec9873da9ef118/flavio/statistics/fits.py#L539
while the multi thread version calls `self.get_predictions_array` without arguments, thus using the default values `par=True, nuisance=True, wc=True`,
https://github.com/flav-io/flavio/blob/9a6b071d9f88362dffdbdfd5faec9873da9ef118/flavio/statistics/fits.py#L544
https://github.com/flav-io/flavio/blob/9a6b071d9f88362dffdbdfd5faec9873da9ef118/flavio/statistics/fits.py#L319
where the crucial argument is `wc=True`. Due to this argument, running in SMEFT is performed for each calculation of observable predictions, which can increase the calculation time by several orders of magnitude.

**Comment by peterstangl** [comment]
This is related to issue #42, but it is a somewhat different problem.

I'm not sure how the bug that a wc_function is assumed to return vanishing Wilson coefficients for vanishing arguments is exactly related to this.

**Comment by DavidMStraub** [comment]
Hm, this is a bit surprising to me since even when using `wc=True`, the Wilson coefficients should still have value 0, so no running should be performed. It could be that it is just the part of the SMEFT running that determines the SM parameters that slows it down.

How to tried snakeviz to check which function calls (in wilson) take most of the time?

**Comment by DavidMStraub** [comment]
OK you are right! Prior to v0.28 (before wilson), zero WCs were not run so this made no difference. So this should actually be implemented in wilson. But in addition it certainly makes sense to fix this in flavio as well by using `wc=False`.

**Comment by DavidMStraub** [comment]
Oh right, it's time to cherry-pick that commit.

**Comment by DavidMStraub** [comment]
Thinking twice about it, I added your suggested change without cherry-pciking the other one.

**Comment by DavidMStraub** [comment]
Closed by #47.
