### ISSUE TITLE
possible bug in C7,C7' flavio->EOS conversion

### ISSUE THREAD

**Issue by bednya** [flav-io/flavio#84]
According to (outdated?)

https://wcxf.github.io/assets/pdf/WET.EOS.pdf

and 

https://wcxf.github.io/assets/pdf/WET.flavio.pdf

C7_bs (C7p_bs) in Flavio corresponds to the same operator as b->s::c7 (b->s::c7') in EOS.

However, when I run the code

```
import flavio
import wilson
wcF = flavio.WilsonCoefficients()
wcF.set_initial(scale=3,wc_dict={'C7_bs':1})
wcF.wc.translate('JMS').translate('EOS')

```
I've got a non-zero c7', i.e,

'b->s::c7': (1.00036571+0j),
"b->s::c7'": (-0.01912714+0j)

I would be grateful, if you help me with this issue...

All the best,
   Alexander
P.S. Just tested with flavio-1.3.1, wilson-1.7, wcxf-1.6 from PyPi.

**Comment by DavidMStraub** [comment]
Thanks for reporting. This is definitely not a flavio bug; indeed I suspect it is just a wrong definition in the basis PDF.

@jasonaebischerGIT & @dvandyk, there is a discrepancy between the definition of the dipole operators in eq. (5.10) of [the manual](https://eos.github.io/manual/manual.pdf) and the [WCxf basis file](https://wcxf.github.io/assets/pdf/WET.EOS.pdf). The translator seems to be correct based on the manual. Right?

**Comment by dvandyk** [comment]
Thanks indeed for the report!

@DavidMStraub The documentation of the basis in EOS seems correct to me, but I will double check with @cBobeth.

**Comment by jasonaebischerGIT** [comment]
Thanks for the report also from my side!
I just checked the translator and it is compatible with what is given in the EOS manual, so the WCxf basis file is indeed outdated. One would have to add the terms proportional to the charm mass to O7, O7', O8, and O8'.

**Comment by DavidMStraub** [comment]
@dvandyk informed us that actually the WCxf basis file is correct after all, but the EOS manual is incorrect. Unfortunately, the WCxf translator is based on the definition in the latter, so this is indeed a bug, but in the wilson package. We will continue to track it there.
