### ISSUE TITLE
Implementation of B(s) -> ll gamma

### ISSUE THREAD

**Issue by mreboud** [flav-io/flavio#90]
LHCb will measure the branching ratio of the decay B(s) -> mu mu gamma and I would like to add it to Flavio.
I will create a new file from bdecays/bpll.py called bllgamma.py and implement the SM prediction as computed in [hep-ph/0410146](https://arxiv.org/pdf/hep-ph/0410146.pdf). Concerning the form factors, should I create a new directory in bdecays/formfactors/ ?

**Comment by DavidMStraub** [comment]
Great!

> Concerning the form factors, should I create a new directory in bdecays/formfactors/ ?

Yes, that would make sense.

**Comment by mreboud** [comment]
I opened a MR, but the implementation is still in progress.

**Comment by DavidMStraub** [comment]
Fixed by #91.
