### ISSUE TITLE
wcxf dependency problem

### ISSUE THREAD

**Issue by peterstangl** [flav-io/flavio#95]
@DavidMStraub, I just noticed that due to the old commit https://github.com/flav-io/flavio/commit/7e3d7e969a373c5bd7536fd7c3d43fbf449612e5, flavio does not depend explicitly on wcxf anymore. However, before commit https://github.com/flav-io/flavio/commit/13759cc83a2faf54d51eabbc24fefaa2fbb37a40 flavio imports wcxf. This leads to the problem that if wilson v2.0 is installed during the installation of flavio v1.1-v1.6 (i.e. it affects the current flavio version on PyPI), the wcxf wrapper package will *not* be installed (since wilson 2.0 doesn't depend on wcxf anymore). In this case, flavio is unusable until wcxf is installed manually.

Possible solutions:
- release a new (minor) flavio version such that at least the newest version includes commits https://github.com/flav-io/flavio/commit/13759cc83a2faf54d51eabbc24fefaa2fbb37a40 and https://github.com/flav-io/flavio/commit/bc55b3c91a6bb85e7ebf6dbc0e492d8cfc9a3cef
- release a new (minor) wilson version that requires the wcxf wrapper package such that a flavio installation that installs the newest wilson version will also install the wcxf wrapper

Probably the first solution is the preferable one. In any case, this is only a problem if one tries to use flavio v1.1-v1.6 together with wilson 2.0 without having wcxf installed.

**Comment by DavidMStraub** [comment]
I see, this is unfortunate. However, I expect that we can release flavio 2.0 on Monday or Tuesday, so I suggest to ignore this problem for a few more days.

**Comment by DavidMStraub** [comment]
Solved by the imminent v2.0 release.
