### ISSUE TITLE
Transfer of ownership

### ISSUE THREAD

**Issue by DavidMStraub** [flav-io/flavio#99]
@peterstangl, do you have a PyPI account? If not, can you please set one up? I want to give you release permissions.

**Comment by peterstangl** [comment]
I just set one up: https://pypi.org/user/peterstangl/

**Comment by DavidMStraub** [comment]
:+1:

BTW, I added a deploy script in 2cb50eb242de26a1eb37a291660da05f4b519671.

You can try it out if you want. Just give me 5 minutes to set up the permissions on PyPI.

**Comment by DavidMStraub** [comment]
>  Error User 'peterstangl' does not have a verified primary email address and cannot be added as a Owner for project

**Comment by peterstangl** [comment]
> > Error User 'peterstangl' does not have a verified primary email address and cannot be added as a Owner for project

It is verified now.

**Comment by DavidMStraub** [comment]
I just removed myself as a collaborator from the flavio repo, so I'll work with PRs from now on.
